# Generated by Django 4.1.5 on 2023-01-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Natioanlity',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
