# Generated by Django 4.1.5 on 2023-01-24 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
